#! /bin/sh
#   -R = Rock Ridge
#   -J = Joliet
#  re charsets: UTF-8 is not available
#  ISO image written to standard output.
exec mkisofs \
 -R \
 -uid 0 \
 -gid 0 \
 -file-mode 0444 \
 -dir-mode 0555 \
 -new-dir-mode 0555 \
 -J \
 -input-charset iso8859-1 \
 -output-charset iso8859-1 \
 -quiet \
 "$1"
