#! /usr/bin/env python3
#
# Given a HTML email message in .eml format, extract the message body
# into a .html file.

import email
import sys

msg = email.message_from_file(sys.stdin)
for part in msg.walk():
    if part.get_content_type() == "text/html":
        sys.stdout.buffer.write(part.get_payload(decode=True))
